name: Publish Package
on:
  release:
    types: [published, prereleased]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.SERVICE_GITHUB_TOKEN}}

      - run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@mattersupply'
      - run: yarn
      - run: yarn build
      - run: yarn version --new-version ${VERSION} --no-git-tag-version

      - run: yarn publish
        if: github.event.release.prerelease == false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - run: yarn publish --tag next
      #   if: github.event.release.prerelease == true
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-version:
    needs: build-and-publish
    runs-on: ubuntu-latest

    if: github.event.release.prerelease == false

    env:
      CI_COMMIT_MESSAGE: 'Update version post release'
      CI_COMMIT_AUTHOR: CI Bot <ci@msco.dev>

    steps:
      - name: Setup Git
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"

      - name: Bump Version
        run: yarn version --prerelease --preid pre --no-git-tag-version

      - name: Push Version Change
        run: |
          git add package.json
          git commit -m "${CI_COMMIT_MESSAGE}"
          git push origin HEAD:master
