name: Update Documentation

on:
  push:
    branches: [master]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      CI_COMMIT_MESSAGE: Update README.md
      CI_COMMIT_AUTHOR: CI

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - run: yarn
      - run: yarn build
      - run: yarn update-readme

      - name: Commit README.md
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
