name: Update Documentation

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      CI_COMMIT_MESSAGE: Update README.md
      CI_COMMIT_AUTHOR: CI

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - run: yarn
      - run: yarn build
      - run: yarn update-readme

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.CI_COMMIT_MESSAGE }}
          committer: ${{ env.CI_COMMIT_AUTHOR }}
          title: ${{ env.CI_COMMIT_MESSAGE }}
          body: |
            This is an automated pull request to update the README.md file.
          branch: update-readme
          branch-suffix: timestamp
          delete-branch: true
          labels: |
            documentation
            automated pr
