on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
name: Create Weekly Pre-Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - run: yarn
      - run: yarn build

      - name: Create weekly version
        run: |
          yarn version --prerelease --preid pre --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=v${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${VERSION}
          release_name: Release ${VERSION}
          body: |
            Weekly Build
          draft: true
          prerelease: true
