on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
name: Create Weekly Pre-Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    env:
      CI_COMMIT_MESSAGE: 'Weekly Release'
      CI_COMMIT_AUTHOR: CI Bot <ci@msco.dev>

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SERVICE_GITHUB_TOKEN }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - run: yarn
      - run: yarn build

      - name: Create weekly version
        run: |
          yarn version --prerelease --preid pre --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=v${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body: |
            Weekly Build
          draft: false
          prerelease: true

      - name: Push Version Change
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add package.json README.md
          git commit -m "${CI_COMMIT_MESSAGE}"
          git push
